#!/bin/bash
# ==============================================================================
#  IGOR — modules/nextcloud_docker/config/nextcloud.yml.tpl
#
#  Bash-heredoc compose generator.  Source this file, then call:
#
#      _nc_render_compose > "${stack_dir}/docker-compose.yml"
#
#  Requires NC_TIER_* variables to be set (source lib/tier_config.sh first).
#  Uses NC_DATA (user data bind path) and NC_UID from the igor environment.
#
#  Volume strategy (NC_TIER_VOLUME_STRATEGY):
#    named — nextcloud + db are Docker named volumes (constrained / standard)
#    bind  — nextcloud + db use host paths under NC_TIER_DATA_PATH (comfortable / server)
#  Redis is always a named volume regardless of tier (ephemeral cache).
# ==============================================================================

_nc_render_compose() {
    local _strategy="${NC_TIER_VOLUME_STRATEGY:-named}"
    local _data_path="${NC_TIER_DATA_PATH}"
    local _nc_data="${NC_DATA:-/mnt/nextclouddata/next}"
    local _redis_mem="${NC_TIER_REDIS_MEMORY:-64m}"
    local _secrets_rel="../../../secrets"

    if [ "$_strategy" = "bind" ]; then
        _nc_render_compose_bind "$_data_path" "$_nc_data" "$_redis_mem" "$_secrets_rel"
    else
        _nc_render_compose_named "$_nc_data" "$_redis_mem" "$_secrets_rel"
    fi
}

# ── Named-volume variant ───────────────────────────────────────────────────────
_nc_render_compose_named() {
    local _nc_data="$1" _redis_mem="$2" _secrets_rel="$3"
    cat <<YAML
# Generated by Igor — tier: ${IGOR_TIER:-constrained} (named volumes)
# Edit via Menu S (Setup & Infra) or regenerate with: igor install
name: nextcloud

services:

  # ── PostgreSQL ──────────────────────────────────────────────────────────────
  db:
    image: postgres:16-alpine
    restart: always
    command: >-
      postgres
      -c shared_buffers=${NC_TIER_DB_SHARED_BUFFERS}
      -c work_mem=${NC_TIER_DB_WORK_MEM}
      -c effective_cache_size=${NC_TIER_DB_EFFECTIVE_CACHE_SIZE}
      -c max_connections=${NC_TIER_DB_MAX_CONNECTIONS}
    volumes:
      - db:/var/lib/postgresql/data:Z
    networks:
      - nextcloud_network
    env_file:
      - ${_secrets_rel}/db.env

  # ── Redis (session cache + file locking) ────────────────────────────────────
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --maxmemory ${_redis_mem} --maxmemory-policy allkeys-lru
    networks:
      - nextcloud_network
    volumes:
      - redis:/data

  # ── Nextcloud FPM ───────────────────────────────────────────────────────────
  app:
    build: .
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      - ${_nc_data}:/var/www/html/data:rw
      - ./config/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-igor.conf:ro
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - ${_secrets_rel}/db.env
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_network

  # ── Nginx ───────────────────────────────────────────────────────────────────
  web:
    image: nginx:alpine-slim
    restart: always
    ports:
      - "8080:80"
    entrypoint: >
      sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:z,ro
      - ${_nc_data}:/var/www/html/data:ro
    depends_on:
      - app
    networks:
      - nextcloud_network

  # ── Cron ────────────────────────────────────────────────────────────────────
  cron:
    build: .
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      - ${_nc_data}:/var/www/html/data:rw
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - ${_secrets_rel}/db.env
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_network

  # ── OnlyOffice (profile: extra — off by default) ────────────────────────────
  onlyoffice:
    image: onlyoffice/documentserver:7.5.1
    container_name: onlyoffice_documentserver
    restart: always
    profiles:
      - extra
    expose:
      - "80"
    environment:
      - JWT_ENABLED=true
      - JWT_HEADER=Authorization
      - WOPI_ENABLED=false
    env_file:
      - ${_secrets_rel}/onlyoffice.env
    networks:
      - nextcloud_network
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_logs:/var/log/onlyoffice

# ── Named volumes ──────────────────────────────────────────────────────────────
volumes:
  db:
    external: true
    name: nextcloud_db
  nextcloud:
    external: true
    name: nextcloud_data
  redis:
    driver: local
  onlyoffice_data:
    external: true
    name: nextcloud_onlyoffice_data
  onlyoffice_logs:
    external: true
    name: nextcloud_onlyoffice_logs

# ── Network ────────────────────────────────────────────────────────────────────
networks:
  nextcloud_network:
    driver: bridge
YAML
}

# ── Bind-mount variant ─────────────────────────────────────────────────────────
_nc_render_compose_bind() {
    local _data_path="$1" _nc_data="$2" _redis_mem="$3" _secrets_rel="$4"
    local _app_dir="${_data_path}/app"
    local _db_dir="${_data_path}/db"
    cat <<YAML
# Generated by Igor — tier: ${IGOR_TIER:-comfortable} (bind mounts)
# Edit via Menu S (Setup & Infra) or regenerate with: igor install
# Host paths:
#   app data : ${_app_dir}
#   db data  : ${_db_dir}
name: nextcloud

services:

  # ── PostgreSQL ──────────────────────────────────────────────────────────────
  db:
    image: postgres:16-alpine
    restart: always
    command: >-
      postgres
      -c shared_buffers=${NC_TIER_DB_SHARED_BUFFERS}
      -c work_mem=${NC_TIER_DB_WORK_MEM}
      -c effective_cache_size=${NC_TIER_DB_EFFECTIVE_CACHE_SIZE}
      -c max_connections=${NC_TIER_DB_MAX_CONNECTIONS}
    volumes:
      - type: bind
        source: ${_db_dir}
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    networks:
      - nextcloud_network
    env_file:
      - ${_secrets_rel}/db.env

  # ── Redis (session cache + file locking) ────────────────────────────────────
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --maxmemory ${_redis_mem} --maxmemory-policy allkeys-lru
    networks:
      - nextcloud_network
    volumes:
      - redis:/data

  # ── Nextcloud FPM ───────────────────────────────────────────────────────────
  app:
    build: .
    restart: always
    volumes:
      - type: bind
        source: ${_app_dir}
        target: /var/www/html
        bind:
          create_host_path: true
      - ${_nc_data}:/var/www/html/data:rw
      - ./config/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-igor.conf:ro
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - ${_secrets_rel}/db.env
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_network

  # ── Nginx ───────────────────────────────────────────────────────────────────
  web:
    image: nginx:alpine-slim
    restart: always
    ports:
      - "8080:80"
    entrypoint: >
      sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - type: bind
        source: ${_app_dir}
        target: /var/www/html
        read_only: true
      - ${_nc_data}:/var/www/html/data:ro
    depends_on:
      - app
    networks:
      - nextcloud_network

  # ── Cron ────────────────────────────────────────────────────────────────────
  cron:
    build: .
    restart: always
    volumes:
      - type: bind
        source: ${_app_dir}
        target: /var/www/html
      - ${_nc_data}:/var/www/html/data:rw
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - ${_secrets_rel}/db.env
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_network

  # ── OnlyOffice (profile: extra — off by default) ────────────────────────────
  onlyoffice:
    image: onlyoffice/documentserver:7.5.1
    container_name: onlyoffice_documentserver
    restart: always
    profiles:
      - extra
    expose:
      - "80"
    environment:
      - JWT_ENABLED=true
      - JWT_HEADER=Authorization
      - WOPI_ENABLED=false
    env_file:
      - ${_secrets_rel}/onlyoffice.env
    networks:
      - nextcloud_network
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_logs:/var/log/onlyoffice

# ── Named volumes ──────────────────────────────────────────────────────────────
# db and nextcloud/app use bind mounts above; only Redis and OnlyOffice use named volumes.
volumes:
  redis:
    driver: local
  onlyoffice_data:
    external: true
    name: nextcloud_onlyoffice_data
  onlyoffice_logs:
    external: true
    name: nextcloud_onlyoffice_logs

# ── Network ────────────────────────────────────────────────────────────────────
networks:
  nextcloud_network:
    driver: bridge
YAML
}
