#!/bin/bash
# ==============================================================================
#  IGOR — modules/nextcloud_docker/config/nextcloud.config.php.tpl
#
#  Bash-heredoc generator for Nextcloud's system config.  Source this file,
#  then call:
#
#      _nc_render_config_php > /tmp/igor_nc_config.php
#
#  The rendered PHP array is then applied key-by-key via occ:
#
#      _nc_apply_config_php /tmp/igor_nc_config.php
#
#  Requires NC_TIER_* variables (source lib/tier_config.sh first).
#
#  Conditional sections:
#    NC_TIER_ENABLE_PREVIEWS  — preview providers block (omitted when false)
#    NC_TIER_CRON_MODE        — webcron|cron → window 2; system+comfortable → 1;
#                               system+server → 0
# ==============================================================================

_nc_render_config_php() {
    # ── Preview providers block ────────────────────────────────────────────────
    local _preview_block=""
    if [ "${NC_TIER_ENABLE_PREVIEWS:-false}" = "true" ]; then
        _preview_block="
  'enabledPreviewProviders' =>
  [
    'OC\\\\Preview\\\\Image',
    'OC\\\\Preview\\\\Movie',
    'OC\\\\Preview\\\\MP3',
    'OC\\\\Preview\\\\PDF',
    'OC\\\\Preview\\\\TXT',
    'OC\\\\Preview\\\\MarkDown',
  ],
  'preview_max_x' => 1024,
  'preview_max_y' => 1024,
  'preview_libjpeg_quality' => 60,"
    fi

    # ── Maintenance window start hour ─────────────────────────────────────────
    local _window=2
    if [ "${NC_TIER_CRON_MODE:-webcron}" = "system" ]; then
        case "${IGOR_TIER:-constrained}" in
            server)     _window=0 ;;
            comfortable) _window=1 ;;
            *)          _window=1 ;;
        esac
    fi

    # ── Cron type ──────────────────────────────────────────────────────────────
    local _cron_type
    case "${NC_TIER_CRON_MODE:-webcron}" in
        webcron) _cron_type="webcron" ;;
        *)       _cron_type="cron"    ;;
    esac

    cat <<PHP
<?php
// Generated by Igor — tier: ${IGOR_TIER:-constrained}
// Applied via occ config:system:set during installation.
// Do not edit this file directly; use Menu 7 (Configure) or re-run the wizard.
\$CONFIG = [
  // ── Cron ──────────────────────────────────────────────────────────────────
  'backgroundjobs_mode'      => '${_cron_type}',
  'maintenance_window_start' => ${_window},
${_preview_block}
  // ── Performance ───────────────────────────────────────────────────────────
  'memcache.local'           => '\\\\OC\\\\Memcache\\\\APCu',
  'memcache.locking'         => '\\\\OC\\\\Memcache\\\\Redis',
  'redis' =>
  [
    'host' => 'redis',
    'port' => 6379,
  ],
  'filelocking.enabled'      => true,

  // ── Logging ───────────────────────────────────────────────────────────────
  'log_type'                 => 'file',
  'logfile'                  => '/var/www/html/data/nextcloud.log',
  'loglevel'                 => 2,
  'log_rotate_size'          => 104857600,

  // ── Security ──────────────────────────────────────────────────────────────
  'overwriteprotocol'        => 'https',
  'default_phone_region'     => 'US',

  // ── Limits ────────────────────────────────────────────────────────────────
  'upload_tmp_dir'           => '/tmp',
  'tempdirectory'            => '/tmp',
];
PHP
}

# ── _nc_apply_config_php ───────────────────────────────────────────────────────
# Parse a rendered config.php and apply each key via occ config:system:set.
# Must be called after Nextcloud is installed and the app container is running.
# Usage: _nc_apply_config_php <rendered_php_file>
_nc_apply_config_php() {
    local _file="${1:-}"
    [ -f "$_file" ] || { warn "_nc_apply_config_php: file not found: ${_file}"; return 1; }

    local _root="${IGOR_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
    local _occ="docker compose -f ${IGOR_STACKS:-${_root}/config/stacks}/nextcloud/docker-compose.yml \
        exec -T -u www-data app php occ"

    step "Applying Nextcloud system config (tier: ${IGOR_TIER:-constrained})"

    # backgroundjobs_mode
    local _cron_type; _cron_type=$(grep "'backgroundjobs_mode'" "$_file" \
        | sed "s/.*=> *'\\([^']*\\)'.*/\\1/")
    [ -n "$_cron_type" ] && \
        $_occ config:system:set backgroundjobs_mode --value="$_cron_type" \
            --type=string 2>/dev/null && ok "  backgroundjobs_mode = ${_cron_type}" || true

    # maintenance_window_start
    local _window; _window=$(grep "'maintenance_window_start'" "$_file" \
        | sed 's/.*=> *\([0-9]*\).*/\1/')
    [ -n "$_window" ] && \
        $_occ config:system:set maintenance_window_start --value="$_window" \
            --type=integer 2>/dev/null && ok "  maintenance_window_start = ${_window}" || true

    # memcache.local
    $_occ config:system:set memcache.local \
        --value='\OC\Memcache\APCu' --type=string 2>/dev/null \
        && ok "  memcache.local = APCu" || true

    # memcache.locking
    $_occ config:system:set memcache.locking \
        --value='\OC\Memcache\Redis' --type=string 2>/dev/null \
        && ok "  memcache.locking = Redis" || true

    # redis host/port
    $_occ config:system:set redis host --value='redis' --type=string 2>/dev/null || true
    $_occ config:system:set redis port --value=6379   --type=integer 2>/dev/null || true
    ok "  redis = redis:6379"

    # filelocking
    $_occ config:system:set filelocking.enabled --value=true --type=boolean 2>/dev/null \
        && ok "  filelocking.enabled = true" || true

    # overwriteprotocol
    $_occ config:system:set overwriteprotocol --value='https' --type=string 2>/dev/null \
        && ok "  overwriteprotocol = https" || true

    # Preview providers (only when enabled)
    if [ "${NC_TIER_ENABLE_PREVIEWS:-false}" = "true" ]; then
        local -a _providers=(
            'OC\Preview\Image'
            'OC\Preview\Movie'
            'OC\Preview\MP3'
            'OC\Preview\PDF'
            'OC\Preview\TXT'
            'OC\Preview\MarkDown'
        )
        local _i=0
        for _p in "${_providers[@]}"; do
            $_occ config:system:set enabledPreviewProviders "$_i" \
                --value="$_p" --type=string 2>/dev/null || true
            _i=$(( _i + 1 ))
        done
        $_occ config:system:set preview_max_x --value=1024 --type=integer 2>/dev/null || true
        $_occ config:system:set preview_max_y --value=1024 --type=integer 2>/dev/null || true
        $_occ config:system:set preview_libjpeg_quality --value=60 --type=integer 2>/dev/null || true
        ok "  preview providers enabled (${#_providers[@]} providers)"
    else
        ok "  preview providers: disabled (tier ${IGOR_TIER:-constrained})"
    fi

    ok "System config applied."
}
